In [1]:
import pandas as pd

In [52]:
df = pd.read_csv("/home/thaddaus/code/cood/notebooks/table_data.csv")

In [50]:
df.head()

,Name,Tags,MSE_ID,MSE_all,R2ScoreVW_ID,R2ScoreVW_all,seed,model.monolithic,model.reuse_phi
0,Orthogonal Compositional (Alpha),"2 slots, AlphaAdd, paper",0.018128,0.026749,-0.126910,-0.063260,4,False,True
1,Orthogonal Compositional (Alpha),"2 slots, AlphaAdd, paper",0.000265,0.000522,0.983610,0.979330,3,False,True
2,Orthogonal Compositional (Alpha),"2 slots, AlphaAdd, paper",0.000270,0.000528,0.983292,0.979065,2,False,True
3,Orthogonal Compositional (Alpha),"2 slots, AlphaAdd, paper",0.018128,0.026749,-0.127007,-0.063349,1,False,True
4,Orthogonal Compositional (Alpha),"2 slots, AlphaAdd, paper",0.000265,0.000522,0.983597,0.979296,0,False,True

In [53]:
res = df.groupby(["Name"], as_index=False).agg({
    "MSE_ID": ["mean", "std"], "MSE_all": ["mean", "std"],
    "R2ScoreVW_ID": ["mean", "std"], "R2ScoreVW_all": ["mean", "std"],
    # "R2Score_ID": ["mean", "std"], "R2Score_all": ["mean", "std"],
})
format_mapping = {
    ("MSE_ID", "mean"): "{:.2e} &",
    ("MSE_ID", "std"): "\\sd{{{:.2e}}} &",
    ("MSE_all", "mean"): "{:.2e} &",
    ("MSE_all", "std"): "\\sd{{{:.2e}}} &",
    ("R2ScoreVW_ID", "mean"): "{:.3f} &",
    ("R2ScoreVW_ID", "std"): "\\sd{{{:.2e}}} &",
    ("R2ScoreVW_all", "mean"): "{:.3f} &",
    ("R2ScoreVW_all", "std"): "\\sd{{{:.2e}}}",
}
res.style.format(format_mapping)